[package]
name = "kafka-rust-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = {version = "0.36.2"}
serde = "1.0.200"
serde_derive = "1.0.200"
serde_json = "1.0.116"
tokio = {version = "1.37.0", features=["full"]}
